package org.tondo.hibernate.test;

import static org.junit.Assert.*;

import java.math.BigDecimal;

import org.junit.Test;
import org.tondo.hibernate.mappings.OneToOneFirst;
import org.tondo.hibernate.mappings.OneToOneSecond;

//Hibernate: create table OneToOneFirst (id bigint generated by default as identity, firstProp varchar(255), primary key (id))
//Hibernate: create table OneToOneSecond (id bigint generated by default as identity, secondProp decimal(19,2), first_id bigint, primary key (id))
//Hibernate: alter table OneToOneSecond add constraint FKh8fy7csvqihrw3a08ts6pdfoo foreign key (first_id) references OneToOneFirst
public class OneToOneMappingTest extends HibernateTestBase {
	
	@Test
	public void testMissingSecond() {
		OneToOneFirst objA = new OneToOneFirst();
		objA.setFirstProp("Ahoj");
		
		assertNull(objA.getId());
		
		manager.getTransaction().begin();
		manager.persist(objA);
		manager.getTransaction().commit();
		
		assertNotNull(objA.getId());
		assertNull(objA.getSecond());
		
		OneToOneFirst foundFromDb = manager.find(OneToOneFirst.class, objA.getId());
		// object returned from internal identity map?
		assertSame(objA, foundFromDb);
	}
	
	@Test
	public void testMissingOwner() {
		OneToOneSecond objB = new OneToOneSecond();
		objB.setSecondProp(BigDecimal.TEN);
		
		manager.getTransaction().begin();
		manager.persist(objB);
		manager.getTransaction().commit();
		
		assertNotNull(objB.getId());
		assertNull(objB.getFirst());
	}
	
	@Test
	public void testSaveOneToOne() {
		OneToOneSecond objB = new OneToOneSecond();
		objB.setSecondProp(BigDecimal.TEN);
		OneToOneFirst objA = new OneToOneFirst();
		objA.setFirstProp("Ahoj");
		objB.setFirst(objA);
		
		manager.getTransaction().begin();
		manager.persist(objA);
		// must be persisted both objects before commit
		manager.persist(objB);
		manager.getTransaction().commit();
		
//		assertNotNull(objB.getId());
//		assertNull(objB.getFirst());
		
		manager.getTransaction().begin();
		OneToOneSecond sec = manager.find(OneToOneSecond.class, objB.getId());
		System.out.println("-- " + sec.getFirst());
	}
}
